# Generated by Django 5.1.4 on 2025-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
