# Generated by Django 5.1.4 on 2025-04-16 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_provider.servicebooking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
        migrations.AddField(
            model_name='subcatagory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='subcatagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcatagory'),
        ),
    ]
