# Generated by Django 5.1.4 on 2025-03-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
